### ISSUE TITLE
REPO Settings 버튼 확인 

### ISSUE THREAD

**Issue by pis03133** [For-MZ/formz-be#1]
** 목적
이슈 테스트.
Settings 버튼이 안 보이네요
권한 문제일거 같긴한데

** 상세 내용
이슈 템플릿 작성하려다가 써봅니다

![!admin](https://github.com/For-MZ/formz-be/assets/70270482/bc9f4be4-c394-4390-aa6b-c98a42ed6924)

**Comment by lalabulla** [comment]
찾아보니 권한문제가 맞네요🥲 
PR 템플릿은 제가 작성할까요?

**Comment by pis03133** [comment]
작성해주시면 감사하죠 ㅎㅎ @lalabulla
