### ISSUE TITLE
Redis 위치 논의(조회수+RefreshToken 저장소로 이용할)

### ISSUE THREAD

**Issue by pis03133** [For-MZ/formz-be#8]
## Issue Details ⚠️

조회수+RefreshToken 저장소로 이용할 Redis를 시스템 아키텍처 어디에 놓을까에 대한 논의
<br>

## Expectation 🎯

저는 redis도 docker에 올리고 싶긴 합니다만 nginx처럼 따로 빼는 방법도 있겠네요
<br>
## Reference link 🗂️

간단하게 Redis란 뭔지에 대해..
https://lucas-owner.tistory.com/56

**Comment by tkfkdgowksel** [comment]
저는 docker에 올리는데 한표 하겠습니다.
관리 측면에서 나을 것 같아서 입니다!

**Comment by lalabulla** [comment]
저도 도커로 올리는거에 동의합니다!
젠킨스나 서버를 도커로 올리는 상황이니 설정이나 관리측면에서 더 좋을 것 같아요!

**Comment by pis03133** [comment]
확인했습니다 전부 도커로 관리하시죠 이슈 닫겠습니다~
